apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: node-app-cert
  namespace: node-app
spec:
  secretName: abc-cert-secret
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: DOMAIN_NAME
  dnsNames:
  - DOMAIN_NAME